#!/usr/bin/with-contenv bash

# Restore the data database if it does not already exist.
if [ -f /data/mai.db ]; then
	echo "mai.db already exists, skipping restore"
else
	echo "No mai.db found, restoring from replica if exists"
	litestream restore -v -if-replica-exists -replica do-spaces /data/mai.db
fi